version: '3.5'
services:
  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANIZATION: "APH Corporation"
      LDAP_DOMAIN: "aph.corp"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_BASE_DN: "dc=aph,dc=corp"
    volumes:
      - /opt/docker/openldap/database:/var/lib/ldap
      - /opt/docker/openldap/conf:/etc/ldap/slapd.d
  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:latest
    ports:
      - 8083:80
      - 8443:443
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap